spring.application.name: shoppingcart
server:
  servlet:
    context-path: /shoppingcart

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

stock:
  products:
    - id: "001"
      name: "Water Bottle"
      price: 24.95
    - id: "002"
      name: "Hoodie"
      price: 65.0
    - id: "003"
      name: "Sticker Set"
      price: 3.99

exchange:
  converterUrl: https://free.currconv.com/api/v7/convert?compact=ultra&apiKey=e0af0a90b8051f3b50b8&q=GBP_EUR,GBP_USD
  enabled: true