import com.example.ipitsik.entity.Product;
import com.example.ipitsik.entity.CartItem;
import com.example.ipitsik.entity.ShoppingCart;

dialect "mvel"

rule "Total cart discount"
    when
        $cart : ShoppingCart(initialPrice > 75.0)
    then
        $cart.setTotalDiscount(10.0);
end

rule "Water bottles discount"
    when
        $s  : ShoppingCart($cartItems : cartItems)
        $ci : CartItem(product.name == "Water Bottle",
            quantity >= 2) from $cartItems
    then
        $ci.setFinalPrice(22.99);
end
